package POJO;
// Generated 17-abr-2014 19:04:36 by Hibernate Tools 3.6.0



/**
 * Apuestas generated by hbm2java
 */
public class Apuestas  implements java.io.Serializable {


     private String idApuesta;
     private String idJugada;
     private String valores;

    public Apuestas() {
    }

    public Apuestas(String idApuesta, String idJugada, String valores) {
       this.idApuesta = idApuesta;
       this.idJugada = idJugada;
       this.valores = valores;
    }
   
    public String getIdApuesta() {
        return this.idApuesta;
    }
    
    public void setIdApuesta(String idApuesta) {
        this.idApuesta = idApuesta;
    }
    public String getIdJugada() {
        return this.idJugada;
    }
    
    public void setIdJugada(String idJugada) {
        this.idJugada = idJugada;
    }
    public String getValores() {
        return this.valores;
    }
    
    public void setValores(String valores) {
        this.valores = valores;
    }




}


