package POJO;
// Generated 17-abr-2014 19:04:36 by Hibernate Tools 3.6.0



/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta  implements java.io.Serializable {


     private DetalleVentaId id;
     private long descuento;
     private long subtotal;
     private String comentario;

    public DetalleVenta() {
    }

    public DetalleVenta(DetalleVentaId id, long descuento, long subtotal, String comentario) {
       this.id = id;
       this.descuento = descuento;
       this.subtotal = subtotal;
       this.comentario = comentario;
    }
   
    public DetalleVentaId getId() {
        return this.id;
    }
    
    public void setId(DetalleVentaId id) {
        this.id = id;
    }
    public long getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(long descuento) {
        this.descuento = descuento;
    }
    public long getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(long subtotal) {
        this.subtotal = subtotal;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


