package POJO;
// Generated 17-abr-2014 19:04:36 by Hibernate Tools 3.6.0



/**
 * DetalleVentaId generated by hbm2java
 */
public class DetalleVentaId  implements java.io.Serializable {


     private String idVenta;
     private String idJugada;

    public DetalleVentaId() {
    }

    public DetalleVentaId(String idVenta, String idJugada) {
       this.idVenta = idVenta;
       this.idJugada = idJugada;
    }
   
    public String getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(String idVenta) {
        this.idVenta = idVenta;
    }
    public String getIdJugada() {
        return this.idJugada;
    }
    
    public void setIdJugada(String idJugada) {
        this.idJugada = idJugada;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleVentaId) ) return false;
		 DetalleVentaId castOther = ( DetalleVentaId ) other; 
         
		 return ( (this.getIdVenta()==castOther.getIdVenta()) || ( this.getIdVenta()!=null && castOther.getIdVenta()!=null && this.getIdVenta().equals(castOther.getIdVenta()) ) )
 && ( (this.getIdJugada()==castOther.getIdJugada()) || ( this.getIdJugada()!=null && castOther.getIdJugada()!=null && this.getIdJugada().equals(castOther.getIdJugada()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdVenta() == null ? 0 : this.getIdVenta().hashCode() );
         result = 37 * result + ( getIdJugada() == null ? 0 : this.getIdJugada().hashCode() );
         return result;
   }   


}


