package POJO;
// Generated 17-abr-2014 19:04:36 by Hibernate Tools 3.6.0



/**
 * Incidencias generated by hbm2java
 */
public class Incidencias  implements java.io.Serializable {


     private String idIncidencia;
     private String idUsuario;
     private String incidencia;
     private int fechaHora;

    public Incidencias() {
    }

    public Incidencias(String idIncidencia, String idUsuario, String incidencia, int fechaHora) {
       this.idIncidencia = idIncidencia;
       this.idUsuario = idUsuario;
       this.incidencia = incidencia;
       this.fechaHora = fechaHora;
    }
   
    public String getIdIncidencia() {
        return this.idIncidencia;
    }
    
    public void setIdIncidencia(String idIncidencia) {
        this.idIncidencia = idIncidencia;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getIncidencia() {
        return this.incidencia;
    }
    
    public void setIncidencia(String incidencia) {
        this.incidencia = incidencia;
    }
    public int getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(int fechaHora) {
        this.fechaHora = fechaHora;
    }




}


