package POJO;
// Generated 17-abr-2014 19:04:36 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Jugadas generated by hbm2java
 */
public class Jugadas  implements java.io.Serializable {


     private String idJugada;
     private String idJuego;
     private Date fechaHora;

    public Jugadas() {
    }

    public Jugadas(String idJugada, String idJuego, Date fechaHora) {
       this.idJugada = idJugada;
       this.idJuego = idJuego;
       this.fechaHora = fechaHora;
    }
   
    public String getIdJugada() {
        return this.idJugada;
    }
    
    public void setIdJugada(String idJugada) {
        this.idJugada = idJugada;
    }
    public String getIdJuego() {
        return this.idJuego;
    }
    
    public void setIdJuego(String idJuego) {
        this.idJuego = idJuego;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }




}


