package POJO;
// Generated 17-abr-2014 19:04:36 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Sesiones generated by hbm2java
 */
public class Sesiones  implements java.io.Serializable {


     private String idSesion;
     private String idUsuario;
     private Date fechaInicio;
     private Date fechaFin;
     private String ip;

    public Sesiones() {
    }

    public Sesiones(String idSesion, String idUsuario, Date fechaInicio, Date fechaFin, String ip) {
       this.idSesion = idSesion;
       this.idUsuario = idUsuario;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.ip = ip;
    }
   
    public String getIdSesion() {
        return this.idSesion;
    }
    
    public void setIdSesion(String idSesion) {
        this.idSesion = idSesion;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }




}


