package POJO;
// Generated 17-abr-2014 19:04:36 by Hibernate Tools 3.6.0



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String idUsuario;
     private String nombreUsuario;
     private String tipoUsuario;
     private String clave;

    public Usuarios() {
    }

    public Usuarios(String idUsuario, String nombreUsuario, String tipoUsuario, String clave) {
       this.idUsuario = idUsuario;
       this.nombreUsuario = nombreUsuario;
       this.tipoUsuario = tipoUsuario;
       this.clave = clave;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


