package POJO;
// Generated 17-abr-2014 19:04:36 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private String idVenta;
     private String idUsuario;
     private Date fechaHora;
     private long total;

    public Ventas() {
    }

    public Ventas(String idVenta, String idUsuario, Date fechaHora, long total) {
       this.idVenta = idVenta;
       this.idUsuario = idUsuario;
       this.fechaHora = fechaHora;
       this.total = total;
    }
   
    public String getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(String idVenta) {
        this.idVenta = idVenta;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }




}


